#!/bin/bash


# For some reason i need to use this when using kitty
export PATH="/opt/homebrew/bin:$PATH"

# Get a list of tmux sessions and pass it to fzf for interactive selection
selected_session=$(tmux list-sessions | awk '{print $1}' | fzf-tmux -p --reverse)

# If a session was selected, attach to it; otherwise, do nothing
if [ -n "$selected_session" ]; then
    tmux switch-client -t "$selected_session"
fi
